// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod scmoa {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_PAYLOAD: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_PAYLOAD: u8 = 4;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PAYLOAD: [Payload; 5] = [
  Payload::NONE,
  Payload::HivemindUpdate,
  Payload::HivemindResult,
  Payload::TopologyMutation,
  Payload::Checkpoint,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Payload(pub u8);
#[allow(non_upper_case_globals)]
impl Payload {
  pub const NONE: Self = Self(0);
  pub const HivemindUpdate: Self = Self(1);
  pub const HivemindResult: Self = Self(2);
  pub const TopologyMutation: Self = Self(3);
  pub const Checkpoint: Self = Self(4);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 4;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::HivemindUpdate,
    Self::HivemindResult,
    Self::TopologyMutation,
    Self::Checkpoint,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::HivemindUpdate => Some("HivemindUpdate"),
      Self::HivemindResult => Some("HivemindResult"),
      Self::TopologyMutation => Some("TopologyMutation"),
      Self::Checkpoint => Some("Checkpoint"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for Payload {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for Payload {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for Payload {
    type Output = Payload;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for Payload {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for Payload {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Payload {}
pub struct PayloadUnionTableOffset {}

pub enum ShardUpdateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ShardUpdate<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ShardUpdate<'a> {
  type Inner = ShardUpdate<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ShardUpdate<'a> {
  pub const VT_SHARD_ID: flatbuffers::VOffsetT = 4;
  pub const VT_STATE: flatbuffers::VOffsetT = 6;
  pub const VT_REWARD: flatbuffers::VOffsetT = 8;
  pub const VT_DONE: flatbuffers::VOffsetT = 10;
  pub const VT_CONTEXT: flatbuffers::VOffsetT = 12;
  pub const VT_SPECIALIST_ID: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ShardUpdate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ShardUpdateArgs<'args>
  ) -> flatbuffers::WIPOffset<ShardUpdate<'bldr>> {
    let mut builder = ShardUpdateBuilder::new(_fbb);
    if let Some(x) = args.context { builder.add_context(x); }
    builder.add_reward(args.reward);
    builder.add_shard_id(args.shard_id);
    builder.add_specialist_id(args.specialist_id);
    builder.add_done(args.done);
    builder.add_state(args.state);
    builder.finish()
  }


  #[inline]
  pub fn shard_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ShardUpdate::VT_SHARD_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn state(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ShardUpdate::VT_STATE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn reward(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(ShardUpdate::VT_REWARD, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn done(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(ShardUpdate::VT_DONE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn context(&self) -> Option<flatbuffers::Vector<'a, f32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f32>>>(ShardUpdate::VT_CONTEXT, None)}
  }
  #[inline]
  pub fn specialist_id(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ShardUpdate::VT_SPECIALIST_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ShardUpdate<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("shard_id", Self::VT_SHARD_ID, false)?
     .visit_field::<u8>("state", Self::VT_STATE, false)?
     .visit_field::<f32>("reward", Self::VT_REWARD, false)?
     .visit_field::<bool>("done", Self::VT_DONE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f32>>>("context", Self::VT_CONTEXT, false)?
     .visit_field::<u8>("specialist_id", Self::VT_SPECIALIST_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct ShardUpdateArgs<'a> {
    pub shard_id: u32,
    pub state: u8,
    pub reward: f32,
    pub done: bool,
    pub context: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f32>>>,
    pub specialist_id: u8,
}
impl<'a> Default for ShardUpdateArgs<'a> {
  #[inline]
  fn default() -> Self {
    ShardUpdateArgs {
      shard_id: 0,
      state: 0,
      reward: 0.0,
      done: false,
      context: None,
      specialist_id: 0,
    }
  }
}

pub struct ShardUpdateBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ShardUpdateBuilder<'a, 'b> {
  #[inline]
  pub fn add_shard_id(&mut self, shard_id: u32) {
    self.fbb_.push_slot::<u32>(ShardUpdate::VT_SHARD_ID, shard_id, 0);
  }
  #[inline]
  pub fn add_state(&mut self, state: u8) {
    self.fbb_.push_slot::<u8>(ShardUpdate::VT_STATE, state, 0);
  }
  #[inline]
  pub fn add_reward(&mut self, reward: f32) {
    self.fbb_.push_slot::<f32>(ShardUpdate::VT_REWARD, reward, 0.0);
  }
  #[inline]
  pub fn add_done(&mut self, done: bool) {
    self.fbb_.push_slot::<bool>(ShardUpdate::VT_DONE, done, false);
  }
  #[inline]
  pub fn add_context(&mut self, context: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ShardUpdate::VT_CONTEXT, context);
  }
  #[inline]
  pub fn add_specialist_id(&mut self, specialist_id: u8) {
    self.fbb_.push_slot::<u8>(ShardUpdate::VT_SPECIALIST_ID, specialist_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ShardUpdateBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ShardUpdateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ShardUpdate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ShardUpdate<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ShardUpdate");
      ds.field("shard_id", &self.shard_id());
      ds.field("state", &self.state());
      ds.field("reward", &self.reward());
      ds.field("done", &self.done());
      ds.field("context", &self.context());
      ds.field("specialist_id", &self.specialist_id());
      ds.finish()
  }
}
pub enum HivemindUpdateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct HivemindUpdate<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HivemindUpdate<'a> {
  type Inner = HivemindUpdate<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> HivemindUpdate<'a> {
  pub const VT_SHARDS: flatbuffers::VOffsetT = 4;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    HivemindUpdate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args HivemindUpdateArgs<'args>
  ) -> flatbuffers::WIPOffset<HivemindUpdate<'bldr>> {
    let mut builder = HivemindUpdateBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    if let Some(x) = args.shards { builder.add_shards(x); }
    builder.finish()
  }


  #[inline]
  pub fn shards(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ShardUpdate<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ShardUpdate>>>>(HivemindUpdate::VT_SHARDS, None)}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(HivemindUpdate::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for HivemindUpdate<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ShardUpdate>>>>("shards", Self::VT_SHARDS, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct HivemindUpdateArgs<'a> {
    pub shards: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ShardUpdate<'a>>>>>,
    pub step_id: u64,
}
impl<'a> Default for HivemindUpdateArgs<'a> {
  #[inline]
  fn default() -> Self {
    HivemindUpdateArgs {
      shards: None,
      step_id: 0,
    }
  }
}

pub struct HivemindUpdateBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HivemindUpdateBuilder<'a, 'b> {
  #[inline]
  pub fn add_shards(&mut self, shards: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<ShardUpdate<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(HivemindUpdate::VT_SHARDS, shards);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(HivemindUpdate::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HivemindUpdateBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HivemindUpdateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HivemindUpdate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for HivemindUpdate<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("HivemindUpdate");
      ds.field("shards", &self.shards());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum ShardResultOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ShardResult<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ShardResult<'a> {
  type Inner = ShardResult<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ShardResult<'a> {
  pub const VT_SHARD_ID: flatbuffers::VOffsetT = 4;
  pub const VT_PREDICTED_STATE: flatbuffers::VOffsetT = 6;
  pub const VT_ACTION: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ShardResult { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ShardResultArgs
  ) -> flatbuffers::WIPOffset<ShardResult<'bldr>> {
    let mut builder = ShardResultBuilder::new(_fbb);
    builder.add_shard_id(args.shard_id);
    builder.add_action(args.action);
    builder.add_predicted_state(args.predicted_state);
    builder.finish()
  }


  #[inline]
  pub fn shard_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ShardResult::VT_SHARD_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn predicted_state(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ShardResult::VT_PREDICTED_STATE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn action(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ShardResult::VT_ACTION, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ShardResult<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("shard_id", Self::VT_SHARD_ID, false)?
     .visit_field::<u8>("predicted_state", Self::VT_PREDICTED_STATE, false)?
     .visit_field::<u8>("action", Self::VT_ACTION, false)?
     .finish();
    Ok(())
  }
}
pub struct ShardResultArgs {
    pub shard_id: u32,
    pub predicted_state: u8,
    pub action: u8,
}
impl<'a> Default for ShardResultArgs {
  #[inline]
  fn default() -> Self {
    ShardResultArgs {
      shard_id: 0,
      predicted_state: 0,
      action: 0,
    }
  }
}

pub struct ShardResultBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ShardResultBuilder<'a, 'b> {
  #[inline]
  pub fn add_shard_id(&mut self, shard_id: u32) {
    self.fbb_.push_slot::<u32>(ShardResult::VT_SHARD_ID, shard_id, 0);
  }
  #[inline]
  pub fn add_predicted_state(&mut self, predicted_state: u8) {
    self.fbb_.push_slot::<u8>(ShardResult::VT_PREDICTED_STATE, predicted_state, 0);
  }
  #[inline]
  pub fn add_action(&mut self, action: u8) {
    self.fbb_.push_slot::<u8>(ShardResult::VT_ACTION, action, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ShardResultBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ShardResultBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ShardResult<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ShardResult<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ShardResult");
      ds.field("shard_id", &self.shard_id());
      ds.field("predicted_state", &self.predicted_state());
      ds.field("action", &self.action());
      ds.finish()
  }
}
pub enum HivemindResultOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct HivemindResult<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for HivemindResult<'a> {
  type Inner = HivemindResult<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> HivemindResult<'a> {
  pub const VT_RESULTS: flatbuffers::VOffsetT = 4;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    HivemindResult { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args HivemindResultArgs<'args>
  ) -> flatbuffers::WIPOffset<HivemindResult<'bldr>> {
    let mut builder = HivemindResultBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    if let Some(x) = args.results { builder.add_results(x); }
    builder.finish()
  }


  #[inline]
  pub fn results(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ShardResult<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ShardResult>>>>(HivemindResult::VT_RESULTS, None)}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(HivemindResult::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for HivemindResult<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ShardResult>>>>("results", Self::VT_RESULTS, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct HivemindResultArgs<'a> {
    pub results: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ShardResult<'a>>>>>,
    pub step_id: u64,
}
impl<'a> Default for HivemindResultArgs<'a> {
  #[inline]
  fn default() -> Self {
    HivemindResultArgs {
      results: None,
      step_id: 0,
    }
  }
}

pub struct HivemindResultBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> HivemindResultBuilder<'a, 'b> {
  #[inline]
  pub fn add_results(&mut self, results: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<ShardResult<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(HivemindResult::VT_RESULTS, results);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(HivemindResult::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> HivemindResultBuilder<'a, 'b> {
    let start = _fbb.start_table();
    HivemindResultBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<HivemindResult<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for HivemindResult<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("HivemindResult");
      ds.field("results", &self.results());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum TopologyMutationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TopologyMutation<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TopologyMutation<'a> {
  type Inner = TopologyMutation<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> TopologyMutation<'a> {
  pub const VT_COMMAND: flatbuffers::VOffsetT = 4;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TopologyMutation { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TopologyMutationArgs<'args>
  ) -> flatbuffers::WIPOffset<TopologyMutation<'bldr>> {
    let mut builder = TopologyMutationBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    if let Some(x) = args.command { builder.add_command(x); }
    builder.finish()
  }


  #[inline]
  pub fn command(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TopologyMutation::VT_COMMAND, None)}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TopologyMutation::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for TopologyMutation<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("command", Self::VT_COMMAND, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct TopologyMutationArgs<'a> {
    pub command: Option<flatbuffers::WIPOffset<&'a str>>,
    pub step_id: u64,
}
impl<'a> Default for TopologyMutationArgs<'a> {
  #[inline]
  fn default() -> Self {
    TopologyMutationArgs {
      command: None,
      step_id: 0,
    }
  }
}

pub struct TopologyMutationBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TopologyMutationBuilder<'a, 'b> {
  #[inline]
  pub fn add_command(&mut self, command: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TopologyMutation::VT_COMMAND, command);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(TopologyMutation::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TopologyMutationBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TopologyMutationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TopologyMutation<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TopologyMutation<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TopologyMutation");
      ds.field("command", &self.command());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum CheckpointOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Checkpoint<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Checkpoint<'a> {
  type Inner = Checkpoint<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Checkpoint<'a> {
  pub const VT_FILEPATH: flatbuffers::VOffsetT = 4;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Checkpoint { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args CheckpointArgs<'args>
  ) -> flatbuffers::WIPOffset<Checkpoint<'bldr>> {
    let mut builder = CheckpointBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    if let Some(x) = args.filepath { builder.add_filepath(x); }
    builder.finish()
  }


  #[inline]
  pub fn filepath(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Checkpoint::VT_FILEPATH, None)}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Checkpoint::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Checkpoint<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("filepath", Self::VT_FILEPATH, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct CheckpointArgs<'a> {
    pub filepath: Option<flatbuffers::WIPOffset<&'a str>>,
    pub step_id: u64,
}
impl<'a> Default for CheckpointArgs<'a> {
  #[inline]
  fn default() -> Self {
    CheckpointArgs {
      filepath: None,
      step_id: 0,
    }
  }
}

pub struct CheckpointBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> CheckpointBuilder<'a, 'b> {
  #[inline]
  pub fn add_filepath(&mut self, filepath: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Checkpoint::VT_FILEPATH, filepath);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(Checkpoint::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> CheckpointBuilder<'a, 'b> {
    let start = _fbb.start_table();
    CheckpointBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Checkpoint<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Checkpoint<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Checkpoint");
      ds.field("filepath", &self.filepath());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum MessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Message<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Message<'a> {
  type Inner = Message<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Message<'a> {
  pub const VT_PAYLOAD_TYPE: flatbuffers::VOffsetT = 4;
  pub const VT_PAYLOAD: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Message { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args MessageArgs
  ) -> flatbuffers::WIPOffset<Message<'bldr>> {
    let mut builder = MessageBuilder::new(_fbb);
    if let Some(x) = args.payload { builder.add_payload(x); }
    builder.add_payload_type(args.payload_type);
    builder.finish()
  }


  #[inline]
  pub fn payload_type(&self) -> Payload {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Payload>(Message::VT_PAYLOAD_TYPE, Some(Payload::NONE)).unwrap()}
  }
  #[inline]
  pub fn payload(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(Message::VT_PAYLOAD, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_hivemind_update(&self) -> Option<HivemindUpdate<'a>> {
    if self.payload_type() == Payload::HivemindUpdate {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { HivemindUpdate::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_hivemind_result(&self) -> Option<HivemindResult<'a>> {
    if self.payload_type() == Payload::HivemindResult {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { HivemindResult::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_topology_mutation(&self) -> Option<TopologyMutation<'a>> {
    if self.payload_type() == Payload::TopologyMutation {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { TopologyMutation::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_checkpoint(&self) -> Option<Checkpoint<'a>> {
    if self.payload_type() == Payload::Checkpoint {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Checkpoint::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for Message<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_union::<Payload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
        match key {
          Payload::HivemindUpdate => v.verify_union_variant::<flatbuffers::ForwardsUOffset<HivemindUpdate>>("Payload::HivemindUpdate", pos),
          Payload::HivemindResult => v.verify_union_variant::<flatbuffers::ForwardsUOffset<HivemindResult>>("Payload::HivemindResult", pos),
          Payload::TopologyMutation => v.verify_union_variant::<flatbuffers::ForwardsUOffset<TopologyMutation>>("Payload::TopologyMutation", pos),
          Payload::Checkpoint => v.verify_union_variant::<flatbuffers::ForwardsUOffset<Checkpoint>>("Payload::Checkpoint", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct MessageArgs {
    pub payload_type: Payload,
    pub payload: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for MessageArgs {
  #[inline]
  fn default() -> Self {
    MessageArgs {
      payload_type: Payload::NONE,
      payload: None,
    }
  }
}

pub struct MessageBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> MessageBuilder<'a, 'b> {
  #[inline]
  pub fn add_payload_type(&mut self, payload_type: Payload) {
    self.fbb_.push_slot::<Payload>(Message::VT_PAYLOAD_TYPE, payload_type, Payload::NONE);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Message::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MessageBuilder<'a, 'b> {
    let start = _fbb.start_table();
    MessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Message<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Message<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Message");
      ds.field("payload_type", &self.payload_type());
      match self.payload_type() {
        Payload::HivemindUpdate => {
          if let Some(x) = self.payload_as_hivemind_update() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Payload::HivemindResult => {
          if let Some(x) = self.payload_as_hivemind_result() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Payload::TopologyMutation => {
          if let Some(x) = self.payload_as_topology_mutation() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Payload::Checkpoint => {
          if let Some(x) = self.payload_as_checkpoint() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("payload", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Message`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn root_as_message(buf: &[u8]) -> Result<Message, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Message>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Message` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_message_unchecked`.
pub fn size_prefixed_root_as_message(buf: &[u8]) -> Result<Message, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Message>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Message` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn root_as_message_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Message<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Message<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Message` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn size_prefixed_root_as_message_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Message<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Message<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Message and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Message`.
pub unsafe fn root_as_message_unchecked(buf: &[u8]) -> Message {
  flatbuffers::root_unchecked::<Message>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Message and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Message`.
pub unsafe fn size_prefixed_root_as_message_unchecked(buf: &[u8]) -> Message {
  flatbuffers::size_prefixed_root_unchecked::<Message>(buf)
}
#[inline]
pub fn finish_message_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<Message<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_message_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<Message<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod scmoa

