// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod scmoa {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_PAYLOAD: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_PAYLOAD: u8 = 8;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PAYLOAD: [Payload; 9] = [
  Payload::NONE,
  Payload::StateUpdate,
  Payload::Action,
  Payload::Prediction,
  Payload::RewardError,
  Payload::TopologyMutation,
  Payload::Checkpoint,
  Payload::Telemetry,
  Payload::InferenceResult,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Payload(pub u8);
#[allow(non_upper_case_globals)]
impl Payload {
  pub const NONE: Self = Self(0);
  pub const StateUpdate: Self = Self(1);
  pub const Action: Self = Self(2);
  pub const Prediction: Self = Self(3);
  pub const RewardError: Self = Self(4);
  pub const TopologyMutation: Self = Self(5);
  pub const Checkpoint: Self = Self(6);
  pub const Telemetry: Self = Self(7);
  pub const InferenceResult: Self = Self(8);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 8;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::StateUpdate,
    Self::Action,
    Self::Prediction,
    Self::RewardError,
    Self::TopologyMutation,
    Self::Checkpoint,
    Self::Telemetry,
    Self::InferenceResult,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::StateUpdate => Some("StateUpdate"),
      Self::Action => Some("Action"),
      Self::Prediction => Some("Prediction"),
      Self::RewardError => Some("RewardError"),
      Self::TopologyMutation => Some("TopologyMutation"),
      Self::Checkpoint => Some("Checkpoint"),
      Self::Telemetry => Some("Telemetry"),
      Self::InferenceResult => Some("InferenceResult"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for Payload {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for Payload {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for Payload {
    type Output = Payload;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for Payload {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for Payload {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Payload {}
pub struct PayloadUnionTableOffset {}

pub enum StateUpdateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct StateUpdate<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for StateUpdate<'a> {
  type Inner = StateUpdate<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> StateUpdate<'a> {
  pub const VT_STATE: flatbuffers::VOffsetT = 4;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 6;
  pub const VT_REWARD: flatbuffers::VOffsetT = 8;
  pub const VT_DONE: flatbuffers::VOffsetT = 10;
  pub const VT_CONTEXT: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    StateUpdate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args StateUpdateArgs<'args>
  ) -> flatbuffers::WIPOffset<StateUpdate<'bldr>> {
    let mut builder = StateUpdateBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    if let Some(x) = args.context { builder.add_context(x); }
    builder.add_reward(args.reward);
    if let Some(x) = args.state { builder.add_state(x); }
    builder.add_done(args.done);
    builder.finish()
  }


  #[inline]
  pub fn state(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(StateUpdate::VT_STATE, None)}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(StateUpdate::VT_STEP_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn reward(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(StateUpdate::VT_REWARD, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn done(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(StateUpdate::VT_DONE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn context(&self) -> Option<flatbuffers::Vector<'a, f32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f32>>>(StateUpdate::VT_CONTEXT, None)}
  }
}

impl flatbuffers::Verifiable for StateUpdate<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("state", Self::VT_STATE, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .visit_field::<f32>("reward", Self::VT_REWARD, false)?
     .visit_field::<bool>("done", Self::VT_DONE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f32>>>("context", Self::VT_CONTEXT, false)?
     .finish();
    Ok(())
  }
}
pub struct StateUpdateArgs<'a> {
    pub state: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub step_id: u64,
    pub reward: f32,
    pub done: bool,
    pub context: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f32>>>,
}
impl<'a> Default for StateUpdateArgs<'a> {
  #[inline]
  fn default() -> Self {
    StateUpdateArgs {
      state: None,
      step_id: 0,
      reward: 0.0,
      done: false,
      context: None,
    }
  }
}

pub struct StateUpdateBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> StateUpdateBuilder<'a, 'b> {
  #[inline]
  pub fn add_state(&mut self, state: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(StateUpdate::VT_STATE, state);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(StateUpdate::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn add_reward(&mut self, reward: f32) {
    self.fbb_.push_slot::<f32>(StateUpdate::VT_REWARD, reward, 0.0);
  }
  #[inline]
  pub fn add_done(&mut self, done: bool) {
    self.fbb_.push_slot::<bool>(StateUpdate::VT_DONE, done, false);
  }
  #[inline]
  pub fn add_context(&mut self, context: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(StateUpdate::VT_CONTEXT, context);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> StateUpdateBuilder<'a, 'b> {
    let start = _fbb.start_table();
    StateUpdateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<StateUpdate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for StateUpdate<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("StateUpdate");
      ds.field("state", &self.state());
      ds.field("step_id", &self.step_id());
      ds.field("reward", &self.reward());
      ds.field("done", &self.done());
      ds.field("context", &self.context());
      ds.finish()
  }
}
pub enum ActionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Action<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Action<'a> {
  type Inner = Action<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Action<'a> {
  pub const VT_ACTION: flatbuffers::VOffsetT = 4;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Action { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ActionArgs<'args>
  ) -> flatbuffers::WIPOffset<Action<'bldr>> {
    let mut builder = ActionBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    if let Some(x) = args.action { builder.add_action(x); }
    builder.finish()
  }


  #[inline]
  pub fn action(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Action::VT_ACTION, None)}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Action::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Action<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("action", Self::VT_ACTION, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct ActionArgs<'a> {
    pub action: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub step_id: u64,
}
impl<'a> Default for ActionArgs<'a> {
  #[inline]
  fn default() -> Self {
    ActionArgs {
      action: None,
      step_id: 0,
    }
  }
}

pub struct ActionBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ActionBuilder<'a, 'b> {
  #[inline]
  pub fn add_action(&mut self, action: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Action::VT_ACTION, action);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(Action::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ActionBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ActionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Action<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Action<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Action");
      ds.field("action", &self.action());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum PredictionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Prediction<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Prediction<'a> {
  type Inner = Prediction<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Prediction<'a> {
  pub const VT_PREDICTED_STATE: flatbuffers::VOffsetT = 4;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Prediction { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args PredictionArgs<'args>
  ) -> flatbuffers::WIPOffset<Prediction<'bldr>> {
    let mut builder = PredictionBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    if let Some(x) = args.predicted_state { builder.add_predicted_state(x); }
    builder.finish()
  }


  #[inline]
  pub fn predicted_state(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Prediction::VT_PREDICTED_STATE, None)}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Prediction::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Prediction<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("predicted_state", Self::VT_PREDICTED_STATE, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct PredictionArgs<'a> {
    pub predicted_state: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub step_id: u64,
}
impl<'a> Default for PredictionArgs<'a> {
  #[inline]
  fn default() -> Self {
    PredictionArgs {
      predicted_state: None,
      step_id: 0,
    }
  }
}

pub struct PredictionBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> PredictionBuilder<'a, 'b> {
  #[inline]
  pub fn add_predicted_state(&mut self, predicted_state: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Prediction::VT_PREDICTED_STATE, predicted_state);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(Prediction::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> PredictionBuilder<'a, 'b> {
    let start = _fbb.start_table();
    PredictionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Prediction<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Prediction<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Prediction");
      ds.field("predicted_state", &self.predicted_state());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum RewardErrorOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RewardError<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RewardError<'a> {
  type Inner = RewardError<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RewardError<'a> {
  pub const VT_PREDICTION_ERROR: flatbuffers::VOffsetT = 4;
  pub const VT_REWARD: flatbuffers::VOffsetT = 6;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RewardError { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RewardErrorArgs
  ) -> flatbuffers::WIPOffset<RewardError<'bldr>> {
    let mut builder = RewardErrorBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    builder.add_reward(args.reward);
    builder.add_prediction_error(args.prediction_error);
    builder.finish()
  }


  #[inline]
  pub fn prediction_error(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(RewardError::VT_PREDICTION_ERROR, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn reward(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(RewardError::VT_REWARD, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RewardError::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for RewardError<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<f32>("prediction_error", Self::VT_PREDICTION_ERROR, false)?
     .visit_field::<f32>("reward", Self::VT_REWARD, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct RewardErrorArgs {
    pub prediction_error: f32,
    pub reward: f32,
    pub step_id: u64,
}
impl<'a> Default for RewardErrorArgs {
  #[inline]
  fn default() -> Self {
    RewardErrorArgs {
      prediction_error: 0.0,
      reward: 0.0,
      step_id: 0,
    }
  }
}

pub struct RewardErrorBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RewardErrorBuilder<'a, 'b> {
  #[inline]
  pub fn add_prediction_error(&mut self, prediction_error: f32) {
    self.fbb_.push_slot::<f32>(RewardError::VT_PREDICTION_ERROR, prediction_error, 0.0);
  }
  #[inline]
  pub fn add_reward(&mut self, reward: f32) {
    self.fbb_.push_slot::<f32>(RewardError::VT_REWARD, reward, 0.0);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(RewardError::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RewardErrorBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RewardErrorBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RewardError<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RewardError<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RewardError");
      ds.field("prediction_error", &self.prediction_error());
      ds.field("reward", &self.reward());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum TopologyMutationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TopologyMutation<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TopologyMutation<'a> {
  type Inner = TopologyMutation<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> TopologyMutation<'a> {
  pub const VT_COMMAND: flatbuffers::VOffsetT = 4;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TopologyMutation { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TopologyMutationArgs<'args>
  ) -> flatbuffers::WIPOffset<TopologyMutation<'bldr>> {
    let mut builder = TopologyMutationBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    if let Some(x) = args.command { builder.add_command(x); }
    builder.finish()
  }


  #[inline]
  pub fn command(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TopologyMutation::VT_COMMAND, None)}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TopologyMutation::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for TopologyMutation<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("command", Self::VT_COMMAND, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct TopologyMutationArgs<'a> {
    pub command: Option<flatbuffers::WIPOffset<&'a str>>,
    pub step_id: u64,
}
impl<'a> Default for TopologyMutationArgs<'a> {
  #[inline]
  fn default() -> Self {
    TopologyMutationArgs {
      command: None,
      step_id: 0,
    }
  }
}

pub struct TopologyMutationBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TopologyMutationBuilder<'a, 'b> {
  #[inline]
  pub fn add_command(&mut self, command: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TopologyMutation::VT_COMMAND, command);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(TopologyMutation::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TopologyMutationBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TopologyMutationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TopologyMutation<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TopologyMutation<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TopologyMutation");
      ds.field("command", &self.command());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum CheckpointOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Checkpoint<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Checkpoint<'a> {
  type Inner = Checkpoint<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Checkpoint<'a> {
  pub const VT_FILEPATH: flatbuffers::VOffsetT = 4;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Checkpoint { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args CheckpointArgs<'args>
  ) -> flatbuffers::WIPOffset<Checkpoint<'bldr>> {
    let mut builder = CheckpointBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    if let Some(x) = args.filepath { builder.add_filepath(x); }
    builder.finish()
  }


  #[inline]
  pub fn filepath(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Checkpoint::VT_FILEPATH, None)}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Checkpoint::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Checkpoint<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("filepath", Self::VT_FILEPATH, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct CheckpointArgs<'a> {
    pub filepath: Option<flatbuffers::WIPOffset<&'a str>>,
    pub step_id: u64,
}
impl<'a> Default for CheckpointArgs<'a> {
  #[inline]
  fn default() -> Self {
    CheckpointArgs {
      filepath: None,
      step_id: 0,
    }
  }
}

pub struct CheckpointBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> CheckpointBuilder<'a, 'b> {
  #[inline]
  pub fn add_filepath(&mut self, filepath: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Checkpoint::VT_FILEPATH, filepath);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(Checkpoint::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> CheckpointBuilder<'a, 'b> {
    let start = _fbb.start_table();
    CheckpointBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Checkpoint<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Checkpoint<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Checkpoint");
      ds.field("filepath", &self.filepath());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum TelemetryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Telemetry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Telemetry<'a> {
  type Inner = Telemetry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Telemetry<'a> {
  pub const VT_GRAVITY: flatbuffers::VOffsetT = 4;
  pub const VT_FRICTION: flatbuffers::VOffsetT = 6;
  pub const VT_REWARD: flatbuffers::VOffsetT = 8;
  pub const VT_ENTROPY: flatbuffers::VOffsetT = 10;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Telemetry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TelemetryArgs
  ) -> flatbuffers::WIPOffset<Telemetry<'bldr>> {
    let mut builder = TelemetryBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    builder.add_entropy(args.entropy);
    builder.add_reward(args.reward);
    builder.add_friction(args.friction);
    builder.add_gravity(args.gravity);
    builder.finish()
  }


  #[inline]
  pub fn gravity(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Telemetry::VT_GRAVITY, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn friction(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Telemetry::VT_FRICTION, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn reward(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Telemetry::VT_REWARD, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn entropy(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Telemetry::VT_ENTROPY, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Telemetry::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Telemetry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<f32>("gravity", Self::VT_GRAVITY, false)?
     .visit_field::<f32>("friction", Self::VT_FRICTION, false)?
     .visit_field::<f32>("reward", Self::VT_REWARD, false)?
     .visit_field::<f32>("entropy", Self::VT_ENTROPY, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct TelemetryArgs {
    pub gravity: f32,
    pub friction: f32,
    pub reward: f32,
    pub entropy: f32,
    pub step_id: u64,
}
impl<'a> Default for TelemetryArgs {
  #[inline]
  fn default() -> Self {
    TelemetryArgs {
      gravity: 0.0,
      friction: 0.0,
      reward: 0.0,
      entropy: 0.0,
      step_id: 0,
    }
  }
}

pub struct TelemetryBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TelemetryBuilder<'a, 'b> {
  #[inline]
  pub fn add_gravity(&mut self, gravity: f32) {
    self.fbb_.push_slot::<f32>(Telemetry::VT_GRAVITY, gravity, 0.0);
  }
  #[inline]
  pub fn add_friction(&mut self, friction: f32) {
    self.fbb_.push_slot::<f32>(Telemetry::VT_FRICTION, friction, 0.0);
  }
  #[inline]
  pub fn add_reward(&mut self, reward: f32) {
    self.fbb_.push_slot::<f32>(Telemetry::VT_REWARD, reward, 0.0);
  }
  #[inline]
  pub fn add_entropy(&mut self, entropy: f32) {
    self.fbb_.push_slot::<f32>(Telemetry::VT_ENTROPY, entropy, 0.0);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(Telemetry::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TelemetryBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TelemetryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Telemetry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Telemetry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Telemetry");
      ds.field("gravity", &self.gravity());
      ds.field("friction", &self.friction());
      ds.field("reward", &self.reward());
      ds.field("entropy", &self.entropy());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum InferenceResultOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct InferenceResult<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for InferenceResult<'a> {
  type Inner = InferenceResult<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> InferenceResult<'a> {
  pub const VT_PREDICTED_STATE: flatbuffers::VOffsetT = 4;
  pub const VT_ACTION: flatbuffers::VOffsetT = 6;
  pub const VT_STEP_ID: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    InferenceResult { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args InferenceResultArgs<'args>
  ) -> flatbuffers::WIPOffset<InferenceResult<'bldr>> {
    let mut builder = InferenceResultBuilder::new(_fbb);
    builder.add_step_id(args.step_id);
    if let Some(x) = args.action { builder.add_action(x); }
    if let Some(x) = args.predicted_state { builder.add_predicted_state(x); }
    builder.finish()
  }


  #[inline]
  pub fn predicted_state(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(InferenceResult::VT_PREDICTED_STATE, None)}
  }
  #[inline]
  pub fn action(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(InferenceResult::VT_ACTION, None)}
  }
  #[inline]
  pub fn step_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(InferenceResult::VT_STEP_ID, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for InferenceResult<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("predicted_state", Self::VT_PREDICTED_STATE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("action", Self::VT_ACTION, false)?
     .visit_field::<u64>("step_id", Self::VT_STEP_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct InferenceResultArgs<'a> {
    pub predicted_state: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub action: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub step_id: u64,
}
impl<'a> Default for InferenceResultArgs<'a> {
  #[inline]
  fn default() -> Self {
    InferenceResultArgs {
      predicted_state: None,
      action: None,
      step_id: 0,
    }
  }
}

pub struct InferenceResultBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> InferenceResultBuilder<'a, 'b> {
  #[inline]
  pub fn add_predicted_state(&mut self, predicted_state: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(InferenceResult::VT_PREDICTED_STATE, predicted_state);
  }
  #[inline]
  pub fn add_action(&mut self, action: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(InferenceResult::VT_ACTION, action);
  }
  #[inline]
  pub fn add_step_id(&mut self, step_id: u64) {
    self.fbb_.push_slot::<u64>(InferenceResult::VT_STEP_ID, step_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> InferenceResultBuilder<'a, 'b> {
    let start = _fbb.start_table();
    InferenceResultBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<InferenceResult<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for InferenceResult<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("InferenceResult");
      ds.field("predicted_state", &self.predicted_state());
      ds.field("action", &self.action());
      ds.field("step_id", &self.step_id());
      ds.finish()
  }
}
pub enum MessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Message<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Message<'a> {
  type Inner = Message<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Message<'a> {
  pub const VT_PAYLOAD_TYPE: flatbuffers::VOffsetT = 4;
  pub const VT_PAYLOAD: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Message { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args MessageArgs
  ) -> flatbuffers::WIPOffset<Message<'bldr>> {
    let mut builder = MessageBuilder::new(_fbb);
    if let Some(x) = args.payload { builder.add_payload(x); }
    builder.add_payload_type(args.payload_type);
    builder.finish()
  }


  #[inline]
  pub fn payload_type(&self) -> Payload {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Payload>(Message::VT_PAYLOAD_TYPE, Some(Payload::NONE)).unwrap()}
  }
  #[inline]
  pub fn payload(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(Message::VT_PAYLOAD, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_state_update(&self) -> Option<StateUpdate<'a>> {
    if self.payload_type() == Payload::StateUpdate {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { StateUpdate::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_action(&self) -> Option<Action<'a>> {
    if self.payload_type() == Payload::Action {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Action::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_prediction(&self) -> Option<Prediction<'a>> {
    if self.payload_type() == Payload::Prediction {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Prediction::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_reward_error(&self) -> Option<RewardError<'a>> {
    if self.payload_type() == Payload::RewardError {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { RewardError::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_topology_mutation(&self) -> Option<TopologyMutation<'a>> {
    if self.payload_type() == Payload::TopologyMutation {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { TopologyMutation::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_checkpoint(&self) -> Option<Checkpoint<'a>> {
    if self.payload_type() == Payload::Checkpoint {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Checkpoint::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_telemetry(&self) -> Option<Telemetry<'a>> {
    if self.payload_type() == Payload::Telemetry {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Telemetry::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_inference_result(&self) -> Option<InferenceResult<'a>> {
    if self.payload_type() == Payload::InferenceResult {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { InferenceResult::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for Message<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_union::<Payload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
        match key {
          Payload::StateUpdate => v.verify_union_variant::<flatbuffers::ForwardsUOffset<StateUpdate>>("Payload::StateUpdate", pos),
          Payload::Action => v.verify_union_variant::<flatbuffers::ForwardsUOffset<Action>>("Payload::Action", pos),
          Payload::Prediction => v.verify_union_variant::<flatbuffers::ForwardsUOffset<Prediction>>("Payload::Prediction", pos),
          Payload::RewardError => v.verify_union_variant::<flatbuffers::ForwardsUOffset<RewardError>>("Payload::RewardError", pos),
          Payload::TopologyMutation => v.verify_union_variant::<flatbuffers::ForwardsUOffset<TopologyMutation>>("Payload::TopologyMutation", pos),
          Payload::Checkpoint => v.verify_union_variant::<flatbuffers::ForwardsUOffset<Checkpoint>>("Payload::Checkpoint", pos),
          Payload::Telemetry => v.verify_union_variant::<flatbuffers::ForwardsUOffset<Telemetry>>("Payload::Telemetry", pos),
          Payload::InferenceResult => v.verify_union_variant::<flatbuffers::ForwardsUOffset<InferenceResult>>("Payload::InferenceResult", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct MessageArgs {
    pub payload_type: Payload,
    pub payload: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for MessageArgs {
  #[inline]
  fn default() -> Self {
    MessageArgs {
      payload_type: Payload::NONE,
      payload: None,
    }
  }
}

pub struct MessageBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> MessageBuilder<'a, 'b> {
  #[inline]
  pub fn add_payload_type(&mut self, payload_type: Payload) {
    self.fbb_.push_slot::<Payload>(Message::VT_PAYLOAD_TYPE, payload_type, Payload::NONE);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Message::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MessageBuilder<'a, 'b> {
    let start = _fbb.start_table();
    MessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Message<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Message<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Message");
      ds.field("payload_type", &self.payload_type());
      match self.payload_type() {
        Payload::StateUpdate => {
          if let Some(x) = self.payload_as_state_update() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Payload::Action => {
          if let Some(x) = self.payload_as_action() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Payload::Prediction => {
          if let Some(x) = self.payload_as_prediction() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Payload::RewardError => {
          if let Some(x) = self.payload_as_reward_error() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Payload::TopologyMutation => {
          if let Some(x) = self.payload_as_topology_mutation() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Payload::Checkpoint => {
          if let Some(x) = self.payload_as_checkpoint() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Payload::Telemetry => {
          if let Some(x) = self.payload_as_telemetry() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Payload::InferenceResult => {
          if let Some(x) = self.payload_as_inference_result() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("payload", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Message`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn root_as_message(buf: &[u8]) -> Result<Message, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Message>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Message` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_message_unchecked`.
pub fn size_prefixed_root_as_message(buf: &[u8]) -> Result<Message, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Message>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Message` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn root_as_message_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Message<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Message<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Message` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn size_prefixed_root_as_message_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Message<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Message<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Message and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Message`.
pub unsafe fn root_as_message_unchecked(buf: &[u8]) -> Message {
  flatbuffers::root_unchecked::<Message>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Message and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Message`.
pub unsafe fn size_prefixed_root_as_message_unchecked(buf: &[u8]) -> Message {
  flatbuffers::size_prefixed_root_unchecked::<Message>(buf)
}
#[inline]
pub fn finish_message_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<Message<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_message_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<Message<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod scmoa

