# automatically generated by the FlatBuffers compiler, do not modify

# namespace: scmoa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Checkpoint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Checkpoint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCheckpoint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Checkpoint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Checkpoint
    def Filepath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Checkpoint
    def StepId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CheckpointStart(builder):
    builder.StartObject(2)

def Start(builder):
    CheckpointStart(builder)

def CheckpointAddFilepath(builder, filepath):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(filepath), 0)

def AddFilepath(builder, filepath):
    CheckpointAddFilepath(builder, filepath)

def CheckpointAddStepId(builder, stepId):
    builder.PrependUint64Slot(1, stepId, 0)

def AddStepId(builder, stepId):
    CheckpointAddStepId(builder, stepId)

def CheckpointEnd(builder):
    return builder.EndObject()

def End(builder):
    return CheckpointEnd(builder)
