# automatically generated by the FlatBuffers compiler, do not modify

# namespace: scmoa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Config(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Config()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Config
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Config
    def LearningRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Config
    def BatchSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Config
    def HiddenDim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Config
    def Nhead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Config
    def NumLayers(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Config
    def NumSpecialists(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Config
    def MaxSeq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Config
    def EntropyCoef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Config
    def MutationThreshold(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ConfigStart(builder):
    builder.StartObject(9)

def Start(builder):
    ConfigStart(builder)

def ConfigAddLearningRate(builder, learningRate):
    builder.PrependFloat32Slot(0, learningRate, 0.0)

def AddLearningRate(builder, learningRate):
    ConfigAddLearningRate(builder, learningRate)

def ConfigAddBatchSize(builder, batchSize):
    builder.PrependUint32Slot(1, batchSize, 0)

def AddBatchSize(builder, batchSize):
    ConfigAddBatchSize(builder, batchSize)

def ConfigAddHiddenDim(builder, hiddenDim):
    builder.PrependUint32Slot(2, hiddenDim, 0)

def AddHiddenDim(builder, hiddenDim):
    ConfigAddHiddenDim(builder, hiddenDim)

def ConfigAddNhead(builder, nhead):
    builder.PrependUint32Slot(3, nhead, 0)

def AddNhead(builder, nhead):
    ConfigAddNhead(builder, nhead)

def ConfigAddNumLayers(builder, numLayers):
    builder.PrependUint32Slot(4, numLayers, 0)

def AddNumLayers(builder, numLayers):
    ConfigAddNumLayers(builder, numLayers)

def ConfigAddNumSpecialists(builder, numSpecialists):
    builder.PrependUint32Slot(5, numSpecialists, 0)

def AddNumSpecialists(builder, numSpecialists):
    ConfigAddNumSpecialists(builder, numSpecialists)

def ConfigAddMaxSeq(builder, maxSeq):
    builder.PrependUint32Slot(6, maxSeq, 0)

def AddMaxSeq(builder, maxSeq):
    ConfigAddMaxSeq(builder, maxSeq)

def ConfigAddEntropyCoef(builder, entropyCoef):
    builder.PrependFloat32Slot(7, entropyCoef, 0.0)

def AddEntropyCoef(builder, entropyCoef):
    ConfigAddEntropyCoef(builder, entropyCoef)

def ConfigAddMutationThreshold(builder, mutationThreshold):
    builder.PrependFloat32Slot(8, mutationThreshold, 0.0)

def AddMutationThreshold(builder, mutationThreshold):
    ConfigAddMutationThreshold(builder, mutationThreshold)

def ConfigEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConfigEnd(builder)
