# automatically generated by the FlatBuffers compiler, do not modify

# namespace: scmoa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HivemindUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HivemindUpdate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHivemindUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HivemindUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HivemindUpdate
    def Shards(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from scmoa.ShardUpdate import ShardUpdate
            obj = ShardUpdate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HivemindUpdate
    def ShardsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HivemindUpdate
    def ShardsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # HivemindUpdate
    def StepId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def HivemindUpdateStart(builder):
    builder.StartObject(2)

def Start(builder):
    HivemindUpdateStart(builder)

def HivemindUpdateAddShards(builder, shards):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shards), 0)

def AddShards(builder, shards):
    HivemindUpdateAddShards(builder, shards)

def HivemindUpdateStartShardsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShardsVector(builder, numElems: int) -> int:
    return HivemindUpdateStartShardsVector(builder, numElems)

def HivemindUpdateAddStepId(builder, stepId):
    builder.PrependUint64Slot(1, stepId, 0)

def AddStepId(builder, stepId):
    HivemindUpdateAddStepId(builder, stepId)

def HivemindUpdateEnd(builder):
    return builder.EndObject()

def End(builder):
    return HivemindUpdateEnd(builder)
