# automatically generated by the FlatBuffers compiler, do not modify

# namespace: scmoa

class Payload(object):
    NONE = 0
    StateUpdate = 1
    Action = 2
    Prediction = 3
    RewardError = 4
    TopologyMutation = 5
    Checkpoint = 6
    Telemetry = 7
