# automatically generated by the FlatBuffers compiler, do not modify

# namespace: scmoa

class Payload(object):
    NONE = 0
    HivemindUpdate = 1
    HivemindResult = 2
    TopologyMutation = 3
    Checkpoint = 4
