# automatically generated by the FlatBuffers compiler, do not modify

# namespace: scmoa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShardResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShardResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShardResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShardResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShardResult
    def ShardId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ShardResult
    def PredictedState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ShardResult
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def ShardResultStart(builder):
    builder.StartObject(3)

def Start(builder):
    ShardResultStart(builder)

def ShardResultAddShardId(builder, shardId):
    builder.PrependUint32Slot(0, shardId, 0)

def AddShardId(builder, shardId):
    ShardResultAddShardId(builder, shardId)

def ShardResultAddPredictedState(builder, predictedState):
    builder.PrependUint8Slot(1, predictedState, 0)

def AddPredictedState(builder, predictedState):
    ShardResultAddPredictedState(builder, predictedState)

def ShardResultAddAction(builder, action):
    builder.PrependUint8Slot(2, action, 0)

def AddAction(builder, action):
    ShardResultAddAction(builder, action)

def ShardResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShardResultEnd(builder)
