# automatically generated by the FlatBuffers compiler, do not modify

# namespace: scmoa

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StateUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StateUpdate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStateUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StateUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StateUpdate
    def State(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # StateUpdate
    def StateAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # StateUpdate
    def StateLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StateUpdate
    def StateIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # StateUpdate
    def StepId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StateUpdate
    def Reward(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # StateUpdate
    def Done(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # StateUpdate
    def Context(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # StateUpdate
    def ContextAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # StateUpdate
    def ContextLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StateUpdate
    def ContextIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def StateUpdateStart(builder):
    builder.StartObject(5)

def Start(builder):
    StateUpdateStart(builder)

def StateUpdateAddState(builder, state):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(state), 0)

def AddState(builder, state):
    StateUpdateAddState(builder, state)

def StateUpdateStartStateVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartStateVector(builder, numElems: int) -> int:
    return StateUpdateStartStateVector(builder, numElems)

def StateUpdateAddStepId(builder, stepId):
    builder.PrependUint64Slot(1, stepId, 0)

def AddStepId(builder, stepId):
    StateUpdateAddStepId(builder, stepId)

def StateUpdateAddReward(builder, reward):
    builder.PrependFloat32Slot(2, reward, 0.0)

def AddReward(builder, reward):
    StateUpdateAddReward(builder, reward)

def StateUpdateAddDone(builder, done):
    builder.PrependBoolSlot(3, done, 0)

def AddDone(builder, done):
    StateUpdateAddDone(builder, done)

def StateUpdateAddContext(builder, context):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(context), 0)

def AddContext(builder, context):
    StateUpdateAddContext(builder, context)

def StateUpdateStartContextVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartContextVector(builder, numElems: int) -> int:
    return StateUpdateStartContextVector(builder, numElems)

def StateUpdateEnd(builder):
    return builder.EndObject()

def End(builder):
    return StateUpdateEnd(builder)
